#!/usr/bin/expect
# function: login root auto.

set ip "192.168.40.246"
set user "admin"
set passwd "qqm@123"
set cmd "display environment"

spawn telnet $ip

expect {

	"Username:"  	 {send "$user\r"; exp_continue}
	"Password:" 	 {send "$passwd\r"; exp_continue}
	"<qqmswitch3700>" { send "\r"; }

}

expect { 
	"<qqmswitch3700>" { send "$cmd\r"; }
}
expect { 
	"<qqmswitch3700>" { send "quit\r"; }
}



